from Tkinter import *
import csv

CSV_FILE = "users.csv"

def show_entry_fields():
   print("Country: %s\n Poll: %s\n Party Name: %s\nParty Label: %s\nParty Color: %s\nSeats Proportion: %s\nExcluded Partners: %s" % (e1.get(), e2.get(), e3.get(), e4.get(), e5.get(), e6.get(), e7.get()))

def read_from_file():
    '''Read csv file and return a list like: [[username, password, count]]'''
    try:
        with open(CSV_FILE, 'rb') as f:
            users = []
            reader = csv.reader(f)
            for row in reader:
                row[2] = int(row[2]) # Make the count an integer so it can increase later
                users.append(row)
            return users
    except IOError:
        popup("Error", "File not found!")

users = []

def write_to_file(users):
    '''Get a list of all users and write it to the csv file'''
    with open(CSV_FILE, 'wb') as f:
        writer = csv.writer(f)
        for row in users:
            row[2] = str(row[2])
        writer.writerows(users)


master = Tk()
Label(master, text="Country").grid(row=0)
Label(master, text="Poll").grid(row=1)
Label(master, text="Party Name").grid(row=2, column=1)
Label(master, text="Party Label").grid(row=2, column=2)
Label(master, text="Party Color").grid(row=2, column=3)
Label(master, text="Seats Proportion").grid(row=2, column=4)
Label(master, text="Excluded Partners").grid(row=2, column=5)
Label(master, text="A").grid(row=3)
Label(master, text="B").grid(row=4)
Label(master, text="C").grid(row=5)
Label(master, text="D").grid(row=6)
Label(master, text="E").grid(row=7)
Label(master, text="F").grid(row=8)
Label(master, text="G").grid(row=9)
Label(master, text="H").grid(row=10)
Label(master, text="I").grid(row=11)
Label(master, text="J").grid(row=12)
Label(master, text="K").grid(row=13)
Label(master, text="L").grid(row=14)
Label(master, text="M").grid(row=15)
Label(master, text="N").grid(row=16)
Label(master, text="O").grid(row=17)
Label(master, text="P").grid(row=18)
Label(master, text="Q").grid(row=19)
Label(master, text="R").grid(row=20)
Label(master, text="S").grid(row=21)
Label(master, text="T").grid(row=22)
Label(master, text="U").grid(row=23)
Label(master, text="V").grid(row=24)
Label(master, text="W").grid(row=25)
Label(master, text="X").grid(row=26)
Label(master, text="Y").grid(row=27)
Label(master, text="Z").grid(row=28)



e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5 = Entry(master)
e6 = Entry(master)
e7 = Entry(master)
e8 = Entry(master)
e9 = Entry(master)
e10 = Entry(master)
e11 = Entry(master)
e12 = Entry(master)
e13 = Entry(master)
e14 = Entry(master)
e15 = Entry(master)
e16 = Entry(master)
e17 = Entry(master)
e18 = Entry(master)
e19 = Entry(master)
e20 = Entry(master)
e21 = Entry(master)
e22 = Entry(master)
e23 = Entry(master)
e24 = Entry(master)
e25 = Entry(master)
e26 = Entry(master)
e27 = Entry(master)
e28 = Entry(master)
e29 = Entry(master)
e30 = Entry(master)
e31 = Entry(master)
e32 = Entry(master)
e33 = Entry(master)
e34 = Entry(master)
e35 = Entry(master)
e36 = Entry(master)
e37 = Entry(master)
e38 = Entry(master)
e39 = Entry(master)
e40 = Entry(master)
e41 = Entry(master)
e42 = Entry(master)
e43 = Entry(master)
e44 = Entry(master)
e45 = Entry(master)
e46 = Entry(master)
e47 = Entry(master)
e48 = Entry(master)
e49 = Entry(master)
e50 = Entry(master)
e51 = Entry(master)
e52 = Entry(master)
e53 = Entry(master)
e54 = Entry(master)
e55 = Entry(master)
e56 = Entry(master)
e57 = Entry(master)

e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=3, column=1)
e4.grid(row=3, column=2)
e5.grid(row=3, column=3)
e6.grid(row=3, column=4)
e7.grid(row=3, column=5)
e8.grid(row=4, column=1)
e9.grid(row=4, column=2)
e10.grid(row=4, column=3)
e11.grid(row=4, column=4)
e12.grid(row=4, column=5)
e13.grid(row=5, column=1)
e14.grid(row=5, column=2)
e15.grid(row=5, column=3)
e16.grid(row=5, column=4)
e17.grid(row=5, column=5)
e18.grid(row=6, column=1)
e19.grid(row=6, column=2)
e20.grid(row=6, column=3)
e21.grid(row=6, column=4)
e22.grid(row=6, column=5)
e23.grid(row=7, column=1)
e24.grid(row=7, column=2)
e25.grid(row=7, column=3)
e26.grid(row=7, column=4)
e27.grid(row=7, column=5)
e28.grid(row=8, column=1)
e29.grid(row=8, column=2)
e30.grid(row=8, column=3)
e31.grid(row=8, column=4)
e32.grid(row=8, column=5)
e33.grid(row=9, column=1)
e34.grid(row=9, column=2)
e35.grid(row=9, column=3)
e36.grid(row=9, column=4)
e37.grid(row=9, column=5)
e38.grid(row=10, column=1)
e39.grid(row=10, column=2)
e40.grid(row=10, column=3)
e41.grid(row=10, column=4)
e42.grid(row=10, column=5)
e43.grid(row=11, column=1)
e44.grid(row=11, column=2)
e45.grid(row=11, column=3)
e46.grid(row=11, column=4)
e47.grid(row=11, column=5)
e48.grid(row=12, column=1)
e49.grid(row=12, column=2)
e50.grid(row=12, column=3)
e51.grid(row=12, column=4)
e52.grid(row=12, column=5)
e53.grid(row=13, column=1)
e54.grid(row=13, column=2)
e55.grid(row=13, column=3)
e56.grid(row=13, column=4)
e57.grid(row=13, column=5)

Button(master, text='Quit', command=master.quit).grid(row=30, column=0, sticky=W, pady=4)
Button(master, text='Show', command=show_entry_fields).grid(row=30, column=1, sticky=W, pady=4)

mainloop( )
